name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    env:
      CI: true
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup yarn
      run: npm install -g yarn
    - name: Install dependencies
      run: yarn install
    - name: Create production build
      run: yarn build --if-present
    - name: Save build as artifact
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: ./dist
